### ISSUE TITLE
change l'adresse mail de contact (paiji@rezometz ou rezo@rezometz) en rezo-admin@rezometz.org

### ISSUE THREAD

**Issue by liusiqi43** [rezometz/paiji2#22]

**Comment by luc--** [comment]
Bon ben ce problème semble clos, non ?

**Comment by luc--** [comment]
En revanche, paiji-dev@rezometz.org ne semble pas être sur sympa.rez :/

**Comment by liusiqi43** [comment]
Je pense ce que @gpichot voulait dire c'est de ne pas coder en dur ce l'adresse mail... donc dans la vue on doit fournir cette addr mail depuis settings.py

**Comment by gpichot** [comment]
Use context processors. This value is required on every page :).

https://docs.djangoproject.com/en/1.7/ref/templates/api/#writing-your-own-context-processors
