### ISSUE TITLE
newsfeed corrections

### ISSUE THREAD

**Issue by lazouz** [rezometz/paiji2#24]
A few propositions : 

Proposer un article au newsfeed -> Proposer un article
L'annonceur -> Auteur
Titre du l'article -> Titre de l'article
Envie du coloriage? Faite-vous le plasir! ->  envie de couleurs ? faites-vous plaisir !

what does "Chemin: p" means ?

**Comment by gpichot** [comment]
"Chemin" shows the HTML tree path.
