### ISSUE TITLE
Add some "comics" modules

### ISSUE THREAD

**Issue by lhark** [rezometz/paiji2#32]
Re-implement the comics from the original paiji, but this time, let the the user choose between a large panel of different webcomics. i was thinking about things like xkcd, cyanide & happiness, dilbert, garfield, SMBC, and others.

**Comment by LGD-Fr** [comment]
moved to django-paiji2-comic repo

**Comment by LGD-Fr** [comment]
And I think lhark has bad tastes, anyway… Only Garfield finds favour in my eyes :-)
