### ISSUE TITLE
Module : mettis

### ISSUE THREAD

**Issue by lhark** [rezometz/paiji2#33]
As it seems for now, the mettis schedule is retrieved through the UI of http://lemet.fr
but this method is a bit ugly to say the least.

Luckily, Metz has an open data policy and is making quite a lot a data available
through the http://data.gouv.fr portal. In particular, they are providing all of the transport
network data under the GTFS format, which is a standardized format developed by Google
for this very purpose. [GTFS reference](https://developers.google.com/transit/gtfs/reference)
In our case, the .zip can be found [here](https://www.data.gouv.fr/fr/datasets/transport-donnees-gtfs/)

Google is even providing a python library that allow for an easy retrieving of the data :
https://github.com/google/transitfeed

The only problem with this method is that it seems it will be hard to automate the retrieving
of the GTFS file (it is apparently renewed every semester) as data.gouv.fr does not provide
an API for this kind of file.

**Comment by gpichot** [comment]
This issue was moved to rezometz/django-paiji2-mettis#1
