### ISSUE TITLE
"Your comment has been successfully saved. " mal placé

### ISSUE THREAD

**Issue by luc--** [rezometz/paiji2#35]
"Your comment has been successfully saved. " n'est pas mis au bon endroit dans la page et du coup, tout est décalé vers le bas lorsque le message est posté, ce qui oblige à cliquer sur la croix pour retrouver l'ordre initial.

Bref, faudrait mettre que le truc apparaisse au niveau de  paiji2/home/templates/home/news-feed.html

**Comment by gpichot** [comment]
Not sure about this one. What is the issue exactly?

**Comment by lhark** [comment]
The message is above the first connection info block, and not above the newsfeed one

**Comment by gpichot** [comment]
Change this file so:
https://github.com/rezometz/paiji2/blob/master/home/templates/home/layout_three_columns.html

Move boostrap_messages before display_alerts. Not after (alerts can be huge and hide the alert on some screens).

**Comment by luc--** [comment]
Vu les changements récents, cette issue n'a plus vraiment lieu d'être, non ? En effet, les commentaires sont désormais placés sans confirmation...
