### ISSUE TITLE
Account recovery doesn't report "Invalid email address"

### ISSUE THREAD

**Issue by liusiqi43** [rezometz/paiji2#46]
People forget their password, and fill in their @supelec.fr email addresses. Except that we only have @metz.supelec.fr on record...

**Comment by gpichot** [comment]
Maybe we should run a commande to change every address ending with @metz.supelec.fr by @supelec.fr.

For me it is not an issue. People should know the address registered in the rezo database (even if it is an alias).

**Comment by liusiqi43** [comment]
This is fixed in the previous commit. 

There are already some people who are confused by this. We told them "an email has been sent", but they haven't received anything.
