### ISSUE TITLE
survey module keeps printing poll options

### ISSUE THREAD

**Issue by liusiqi43** [rezometz/paiji2#47]
better remove it to avoid flooding our error.log but I can't track it down... @gpichot?

**Comment by lhark** [comment]
I couldn't spot the source of the problem either :/

**Comment by lhark** [comment]
Right now i hate at least one django-graphos dev :
i found the origin of the problem :
 /home/lhark/.virtualenvs/paiji2/local/lib/python2.7/site-packages/graphos/sources/model.py(9)get_field_values()
 print values

Now, what's the best way to solve that ?

**Comment by lhark** [comment]
i just remembered we're using gpichot's fork of django-graphos, why exactly are we doing that ?

**Comment by liusiqi43** [comment]
We should fork that to rezometz/graphos, make changes and fork from there instead. Then we just chance the upstream used for paiji2.

**Comment by gpichot** [comment]
I will do it on my repo

**Comment by liusiqi43** [comment]
hmm...I think it's better to gradually migrate all the repositories to rezometz/... overtime people will get confused why we are relying on external repo that we don't have full control over...

**Comment by lhark** [comment]
Yeah, i think it is better to have all the repos in the same place. BTW, i don't even understand why modular-blocks and calendar have separate repos, they can only work with paiji.

**Comment by liusiqi43** [comment]
they can work with other projects.

**Comment by gpichot** [comment]
Done for the print statement (not forking). BTW, I do not like to have all these applications in the same repository (I think to survey, cov etc).
