### ISSUE TITLE
Make the public view "as it must be"

### ISSUE THREAD

**Issue by lazouz** [rezometz/paiji2#48]
The public view (when you're not in Supelec or at the residence, or not connected), is supposed to be a little more "safe", in my opinion : 

- The mailto on the name isn't supposed to appear in public view
- the FTP menu, the "sign up" button "polardator", "integrators", "rezo.rez", "inscription des groupes" , "quotas" are not supposed to be displayed.
- replace "wiki.rez" by "wiki rezo", and the link by "wiki.rezometz.org" : the DNS resolution is impossible from the outside of Supelec.
- maybe, adding a choice "public" or "supelec" or "residence" for the articles visibility could be good ;)

**Comment by gpichot** [comment]
For now, add a .htaccess and .htpasswd with the usual credentials (only for external users).
And add also no index no follow meta data.

**Comment by LGD-Fr** [comment]
> The mailto on the name isn't supposed to appear in public view
It’s corrected with 09b4ac4 and a8f4200

**Comment by LGD-Fr** [comment]
> the FTP menu, the "sign up" button "polardator", "integrators", "rezo.rez", "inscription des groupes" , "quotas" are not supposed to be displayed.

Corrected

**Comment by LGD-Fr** [comment]
> replace "wiki.rez" by "wiki rezo", and the link by "wiki.rezometz.org" : the DNS resolution is impossible from the outside of Supelec.

Corrected

**Comment by LGD-Fr** [comment]
> maybe, adding a choice "public" or "supelec" or "residence" for the articles visibility could be good ;)

TODO ;-)

**Comment by LGD-Fr** [comment]
>   maybe, adding a choice "public" or "supelec" or "residence" for the articles visibility could be good ;)

done
