### ISSUE TITLE
Ressucitate the "FTP" page with the FTP description

### ISSUE THREAD

**Issue by lazouz** [rezometz/paiji2#49]
That page what pretty cool on paiji1 ! 
I don't think that exaclty translating the old page is a good thing, it can be improved in the same time.
This is a good project for N1as, isn't it ?

**Comment by gpichot** [comment]
I agree. I just do not want to see the complexity that we add with retrieving a file on each ftp (even if with can). A simple application that manage an FTPServerModel (url + description) will be sufficient.

**Comment by LGD-Fr** [comment]
-> cf django-paiji2-ftp
