### ISSUE TITLE
Clean requirements

### ISSUE THREAD

**Issue by gpichot** [rezometz/paiji2#54]
Some requirements tagged as "dev" are not dev specific and should be tagged as "prod".

Moreover with the externalisation of applications I think that some package are not directly required by paiji2.

**Comment by LGD-Fr** [comment]
I tried (0fdfa4c) to have a more exact requirements/prod.txt.
I do not know if django-bower and MySQL-python are really required.

**Comment by gpichot** [comment]
Mysql-Python should not a requirement by default as any backend could be used (sqlite or postgresql for instance).

Regarding django-bower, currently it is. But I would like to move to a standalone bower. I do not think that is a real need to have the required libraries written in the settings files.

**Comment by LGD-Fr** [comment]
Ok
