### ISSUE TITLE
Add link to download the rules of the rezo

### ISSUE THREAD

**Issue by lhark** [rezometz/paiji2#66]
The rules state that payment of the participation or usage of our services imply acceptation of our terms. But for this to be at least a tiny legal, we need to provide an easy access to the document : 
http://rezo.rez/files/reglement_fr.pdf
http://rezo.rez/files/reglement_en.pdf

**Comment by LGD-Fr** [comment]
You should provide them these documents *before* they accept :-) You don’t create a rezo account on paiji, so I don't think it's the better place. A printer would do the job !
And why local urls ? It’s not practical at all.
